version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: '${DOCKER_REPO}:${DOCKER_TAG}'
    environment:
      - NODE_ENV
      - PORT
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
    ports:
      - '${PORT}:${PORT}'
    restart: always
